name: Check Comments Language

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: 'Base branch to compare against'
        required: true
        default: 'main'

jobs:
  check-comments:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Нужно для получения diff

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install langdetect

      - name: Run comment checker
        run: python .github/scripts/check_comments.py
